openapi: 3.1.0

info:
  title: Skopeo Machine API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /skopeo_machine/v1/copy:
    post:
      summary: Submit a copy job
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/CopyJob"

      responses:
        "200":
          description: Job submitted successfully
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/CopyJobResponse"
        "400":
          description: Invalid request body
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: The error message
      required:
        - message
    CopyJob:
      type: object
      properties:
        source:
          type: string
          description: The source image to copy from
        target:
          type: string
          description: The target image to copy to
      required:
        - source
        - target
    CopyJobResponse:
      type: object
      properties:
        jobId:
          type: string
          description: The ID of the job
      required:
        - jobId
