/*
 * Skopeo Machine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI interface {

	// SkopeoMachineV1CopyPost Post /skopeo_machine/v1/copy
	// Submit a copy job
	SkopeoMachineV1CopyPost(c *gin.Context)
}
