/*
 * Skopeo Machine API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1

type CopyJob struct {

	// The source image to copy from
	Source string `json:"source"`

	// The target image to copy to
	Target string `json:"target"`
}
